services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devops_db
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/devops_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - devops-network

volumes:
  mysql_data:

networks:
  devops-network:
    driver: bridge
